theme: noesya-hugo-theme
_merge: deep
params:
  ecosystem: lab
  posts:
    date_format: "2006"
    index:
      layout: list
      options:
        categories: false
        image: false
        summary: false